[workspace]
resolver = "2"
members = [
    "horfimbor-eventsource",
    "horfimbor-eventsource-derive",
    "horfimbor-time"]

[workspace.dependencies]
thiserror = "1.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
unwrap_used = "warn"
