[package]
name = "horfimbor-eventsource"
version = "0.2.1"
edition = "2021"
description = "an eventsource implementation on top of eventstore"
repository = "https://github.com/horfimbor/horfimbor-engine"
license-file = "LICENSE"
keywords = ["eventsource", "eventsourcing", "eventstore"]
categories = ["database", "rust-patterns"]

[dependencies]
async-trait = "0.1"
eventstore = "3.0.0"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.1", features = ["v4", "serde"] }
tokio = "1.26"
thiserror = "1.0"
horfimbor-eventsource-derive = { version = "0.1.4", path = "../horfimbor-eventsource-derive" }
redis= { version = "0.26", features = ["tokio-rustls-comp"], optional = true }
chrono = "0.4"

[features]
cache-redis=["redis"]
default = ["cache-redis"]

[dev-dependencies]
lazy_static = "1.4"
rand = "0.8"
